### PR TITLE
fix: check leader before aborting headcount/afk

### LINKED ISSUE #255: If a user tries to end someone else's headcount or AFK check, ask them to confirm before doing so.

### PR DESCRIPTION
**Pull request by nyapat**
closes #255

### CODE REVIEW

**Comment by ewang2002** [comment]
Smh you caught me as I was about to go to sleep. I'll review this tomorrow morning.

File: src/instances/HeadcountInstance.ts [hunk 1]
```diff
@@ -961,19 +1006,28 @@ export class HeadcountInstance {
...
                 }
                 case HeadcountInstance.END_HEADCOUNT_ID: {
-                    LOGGER.info(`${this._leaderName} ended ${this._dungeon.dungeonName} headcount.`);
-                    this.endHeadcount().then();
-                    return;
+                    if (i.user.id !== this._memberInit.id) {
+                        return this.showWrongLeaderbuttons(i);
+                    } else {
+                        LOGGER.info(`${(i.member as GuildMember).nickname} ended ${this._dungeon.dungeonName} headcount.`);
+                        return this.abortHeadcount().then();
```
Comment (ewang2002) [inline src/instances/HeadcountInstance.ts:1029]: Pressing the `End Headcount` button should ask the user if they want to end the headcount, not abort it.

When I press the `End Headcount` button on a headcount that doesn't belong to me, and then confirm that I want to end the headcount, it aborts the headcount.

**Review by ewang2002 — CHANGES_REQUESTED** [review]
So I'm not sure if I'm doing something wrong, but there are several significant issues that need to be addressed.
- If I own a headcount and I attempt to end (**not** abort) my own headcount, the headcount still ends up being aborted. 
- Whenever I press the `End Headcount` or `Abort Headcount` buttons on my own headcount, the bot attempts to reply but it keeps on thinking:

  image

  This should not happen. 

- See my comment in your code. 

Overall, good start but there are some pretty big bugs that need to be resolved. Let me know if you have any questions!

**Review by ewang2002 — CHANGES_REQUESTED** [review]
When I press the "End Headcount" button, ideally "abort" should be replaced with "end":
image

Likewise, when pressing "Delete Headcount," change "abort" to "delete":
image

Basically, it would be nice to have the question text be customizable so it doesn't always say "abort the headcount." 

Otherwise, this PR looks good.

**Review by ewang2002 — APPROVED** [review]
lgtm
